### ISSUE TITLE
en16931-cii2ubl-cli-1.2.2-full.jar throws NoClassDefFoundError

### ISSUE THREAD

**Issue by Lorenzschaef** [phax/en16931-cii2ubl#6]
Hi

I just downloaded en16931-cii2ubl-cli-1.2.2-full.jar and tried to convert a file using the CLI. I'm getting the following error:

```
[main] INFO com.helger.en16931.cii2ubl.cli.CIIToUBLConverter - Starting CII to UBL Converter
Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/DataSource
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:470)
	at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:63)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:128)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:84)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:162)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:92)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:444)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:292)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1138)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:186)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:146)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:350)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:446)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:409)
	at com.helger.jaxb.JAXBContextCacheKey._createFromPackageAndClassLoader(JAXBContextCacheKey.java:155)
	at com.helger.jaxb.JAXBContextCacheKey.createJAXBContext(JAXBContextCacheKey.java:202)
	at com.helger.jaxb.JAXBContextCache.lambda$new$3fed5817$1(JAXBContextCache.java:81)
	at com.helger.commons.cache.MappedCache.getFromCache(MappedCache.java:336)
	at com.helger.jaxb.JAXBContextCache.getFromCache(JAXBContextCache.java:124)
	at com.helger.jaxb.JAXBContextCache.getFromCache(JAXBContextCache.java:166)
	at com.helger.jaxb.builder.AbstractJAXBBuilder.getJAXBContext(AbstractJAXBBuilder.java:164)
	at com.helger.jaxb.builder.JAXBReaderBuilder.createUnmarshaller(JAXBReaderBuilder.java:134)
	at com.helger.jaxb.builder.JAXBReaderBuilder.read(JAXBReaderBuilder.java:165)
	at com.helger.jaxb.IJAXBReader.read(IJAXBReader.java:326)
	at com.helger.jaxb.IJAXBReader.read(IJAXBReader.java:127)
	at com.helger.jaxb.IJAXBReader.read(IJAXBReader.java:97)
	at com.helger.jaxb.IJAXBReader.read(IJAXBReader.java:184)
	at com.helger.en16931.cii2ubl.AbstractCIIToUBLConverter.convertCIItoUBL(AbstractCIIToUBLConverter.java:314)
	at com.helger.en16931.cii2ubl.cli.CIIToUBLConverter.call(CIIToUBLConverter.java:180)
	at com.helger.en16931.cii2ubl.cli.CIIToUBLConverter.call(CIIToUBLConverter.java:55)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at com.helger.en16931.cii2ubl.cli.CIIToUBLConverter.main(CIIToUBLConverter.java:228)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 45 more
```

**Comment by phax** [comment]
Thanks for pointing that out. It's a missing Jakarta activation. I will look at it asap.

**Comment by phax** [comment]
Part of the 1.2.5 release which is currently building.
